#!/bin/bash

# Manage go-licenses version externally for CI
if [ "$CI" != "true" ]; then
    go install github.com/google/go-licenses/v2@latest
fi

# Setup temporary directory for generated license reports
export TEMPDIR="$(mktemp -d)"
trap "rm -fr ${TEMPDIR}" EXIT

# Define GOOS and their corresponding GOARCH values based on .goreleaser.yml
declare -A platform_archs=(
    ["linux"]="386 arm amd64 arm64"
    ["darwin"]="amd64 arm64"
    ["windows"]="386 amd64 arm64"
)

for goos in linux darwin windows ; do
    for goarch in ${platform_archs[$goos]} ; do
        # Note: we ignore warnings because we want the command to succeed, however the output should be checked
        #       for any new warnings, and potentially we may need to add license information.
        #
        #       Normally these warnings are packages containing non go code, which may or may not require explicit attribution,
        #       depending on the license.
        echo "Checking licenses for ${goos}/${goarch}..."
        GOOS="${goos}" GOARCH="${goarch}" go-licenses report ./... --template .github/licenses.tmpl --ignore github.com/cli/cli > "${TEMPDIR}/third-party-licenses.${goos}-${goarch}.md" || echo "Ignore warnings"
        if ! diff -s "${TEMPDIR}/third-party-licenses.${goos}-${goarch}.md" "third-party-licenses.${goos}-${goarch}.md"; then
            echo "::error title=License check failed::Please update the license files by running \`make licenses\` and committing the output."
            exit 1
        fi
    done
done

echo "License check passed for all platforms."
