#!/bin/bash

go install github.com/williammartin/licenseplease/cmd/license-please@latest

export TEMPDIR="$(mktemp -d)"
trap "rm -fr ${TEMPDIR}" EXIT

echo "Checking licenses..."
license-please report > "${TEMPDIR}/third-party-licenses.md"
if ! diff -q "${TEMPDIR}/third-party-licenses.md" "third-party-licenses.md" > /dev/null; then
    echo "::error title=License check failed::Please update the license files by running \`make licenses\` and committing the output."
    exit 1
fi

echo "License check passed."
